include:
  - board: seeeduino_xiao_ble
    shield: around_forty_aaa_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: around_forty_aaa_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset
